export const players = [
  // Goalkeepers
  {
    name: "(1) Adam Fenwick",
    position: "Goalkeeper",
    DOB: "1995-06-12",
    img: "./utils/images/goalkeeper-placeholder.jpg",
    appearances: 25,
    goals: 0,
    assists: 0,
    cleanSheets: 10,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) James Holding",
    position: "Goalkeeper",
    DOB: "1994-11-23",
    img: "./utils/images/goalkeeper-placeholder.jpg",
    appearances: 30,
    goals: 0,
    assists: 0,
    cleanSheets: 12,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 4,
  },
  {
    name: "(1) Tommy Ford",
    position: "Goalkeeper",
    DOB: "1997-03-08",
    img: "./utils/images/goalkeeper-placeholder.jpg",
    appearances: 18,
    goals: 0,
    assists: 0,
    cleanSheets: 5,
    yellowCards: 0,
    redCards: 1,
    manOfTheMatch: 2,
  },

  // Defenders
  {
    name: "(1) Tom Hammond",
    position: "Defender",
    DOB: "1993-09-16",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 28,
    goals: 2,
    assists: 3,
    cleanSheets: 15,
    yellowCards: 4,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Joe Butler",
    position: "Defender",
    DOB: "1996-05-22",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 32,
    goals: 1,
    assists: 2,
    cleanSheets: 18,
    yellowCards: 3,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Scott O'Brien",
    position: "Defender",
    DOB: "1994-02-19",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 35,
    goals: 0,
    assists: 4,
    cleanSheets: 20,
    yellowCards: 5,
    redCards: 1,
    manOfTheMatch: 2,
  },
  {
    name: "(1) Dan Schackleton",
    position: "Defender",
    DOB: "1992-07-30",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 29,
    goals: 3,
    assists: 1,
    cleanSheets: 14,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Joshua Barnett",
    position: "Defender",
    DOB: "1995-01-14",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 33,
    goals: 4,
    assists: 2,
    cleanSheets: 22,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) Cameron Robinson",
    position: "Defender",
    DOB: "1991-11-03",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 36,
    goals: 2,
    assists: 5,
    cleanSheets: 25,
    yellowCards: 3,
    redCards: 0,
    manOfTheMatch: 2,
  },
  {
    name: "(1) Jamie Fozard",
    position: "Defender",
    DOB: "1998-02-21",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 22,
    goals: 1,
    assists: 1,
    cleanSheets: 10,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Tim Malkin",
    position: "Defender",
    DOB: "1990-10-11",
    img: "./utils/images/defender-placeholder.jpg",
    appearances: 40,
    goals: 6,
    assists: 7,
    cleanSheets: 28,
    yellowCards: 6,
    redCards: 0,
    manOfTheMatch: 4,
  },

  // Midfielders
  {
    name: "(1) Danny Kreft",
    position: "Midfielder",
    DOB: "1997-06-05",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 30,
    goals: 5,
    assists: 6,
    cleanSheets: 12,
    yellowCards: 3,
    redCards: 0,
    manOfTheMatch: 2,
  },
  {
    name: "(1) Dan Edmonds",
    position: "Midfielder",
    DOB: "1993-12-13",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 28,
    goals: 3,
    assists: 4,
    cleanSheets: 10,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) Dean Worrall (C)",
    position: "Midfielder",
    DOB: "1990-04-07",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 36,
    goals: 7,
    assists: 10,
    cleanSheets: 20,
    yellowCards: 4,
    redCards: 1,
    manOfTheMatch: 5,
  },
  {
    name: "(1) Adam Franklin",
    position: "Midfielder",
    DOB: "1994-09-09",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 22,
    goals: 4,
    assists: 3,
    cleanSheets: 8,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Jacob Darkes",
    position: "Midfielder",
    DOB: "1996-01-11",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 25,
    goals: 2,
    assists: 5,
    cleanSheets: 12,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) Arjun Varma",
    position: "Midfielder",
    DOB: "1992-08-27",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 38,
    goals: 6,
    assists: 8,
    cleanSheets: 18,
    yellowCards: 3,
    redCards: 0,
    manOfTheMatch: 4,
  },

  {
    name: "Jai Narayan",
    position: "Midfielder",
    DOB: "1991-04-18",
    img: "./utils/images/midfielder-placeholder.jpg",
    appearances: 26,
    goals: 4,
    assists: 3,
    cleanSheets: 15,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 2,
  },

  // Attackers
  {
    name: "(9) Oli Baron",
    position: "Attacker",
    DOB: "1994-06-19",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 28,
    goals: 12,
    assists: 7,
    cleanSheets: 5,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 4,
  },
  {
    name: "(1) Jordan Moore",
    position: "Attacker",
    DOB: "1992-11-25",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 30,
    goals: 9,
    assists: 5,
    cleanSheets: 4,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) Jordan Mercer",
    position: "Attacker",
    DOB: "1993-05-16",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 35,
    goals: 11,
    assists: 8,
    cleanSheets: 3,
    yellowCards: 3,
    redCards: 0,
    manOfTheMatch: 5,
  },
  {
    name: "(1) Andy Pye",
    position: "Attacker",
    DOB: "1991-07-12",
    img: "./utils/images/attacker-placeholder.jpg",
    goals: 5,
    assists: 4,
    cleanSheets: 2,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 2,
  },
  {
    name: "(1) Josh Robinson",
    position: "Attacker",
    DOB: "1994-09-05",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 32,
    goals: 8,
    assists: 6,
    cleanSheets: 3,
    yellowCards: 2,
    redCards: 0,
    manOfTheMatch: 3,
  },
  {
    name: "(1) Cameron Liddell",
    position: "Attacker",
    DOB: "1992-03-22",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 20,
    goals: 2,
    assists: 1,
    cleanSheets: 4,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Harry Whittaker",
    position: "Attacker",
    DOB: "1993-12-01",
    img: "./utils/images/attacker-placeholder.jpg",
    appearances: 22,
    goals: 3,
    assists: 2,
    cleanSheets: 6,
    yellowCards: 1,
    redCards: 0,
    manOfTheMatch: 1,
  },
];
