import goalkeeperPlaceholder from "./utils/images/goalkeeper-placeholder.jpg";
import defenderPlaceholder from "./utils/images/defender-placeholder.jpg";
import midfielderPlaceholder from "./utils/images/midfielder-placeholder.jpg";
import attackerPlaceholder from "./utils/images/attacker-placeholder.jpg";

export const players = [
  // Goalkeepers
  {
    name: "Adam Fenwick",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "James Holding",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Tommy Ford",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },

  // Defenders
  {
    name: "Tom Hammond",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Joe Butler",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Scott O'Brien",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Dan Schackleton",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Joshua Barnett",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Cameron Robinson",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Jamie Fozard",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Tim Malkin",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },

  // Midfielders
  {
    name: "Danny Kreft",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Dan Edmonds",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Dean Worrall (C)",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Adam Franklin",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Jacob Darkes",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Arjun Varma",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Aran Harris",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Jai Narayan",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },

  // Attackers
  {
    name: "Oli Baron",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Jordan Moore",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Jordan Mercer",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Andy Pye",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Josh Robinson",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Cameron Liddell",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    name: "Harry Whittaker",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
  },
];
