import goalkeeperPlaceholder from "./utils/images/goalkeeper-placeholder.jpg";
import defenderPlaceholder from "./utils/images/defender-placeholder.jpg";
import midfielderPlaceholder from "./utils/images/midfielder-placeholder.jpg";
import attackerPlaceholder from "./utils/images/attacker-placeholder.jpg";

export const players = [
  // Goalkeepers
  {
    name: "(1) Adam Fenwick",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) James Holding",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Tommy Ford",
    position: "Goalkeeper",
    DOB: "N/A",
    img: goalkeeperPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },

  // Defenders
  {
    name: "(1) Tom Hammond",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Joe Butler",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Scott O'Brien",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Dan Schackleton",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Joshua Barnett",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Cameron Robinson",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Jamie Fozard",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Tim Malkin",
    position: "Defender",
    DOB: "N/A",
    img: defenderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },

  // Midfielders
  {
    name: "(1) Danny Kreft",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Dan Edmonds",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Dean Worrall (C)",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Adam Franklin",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Jacob Darkes",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Arjun Varma",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },

  {
    name: "Jai Narayan",
    position: "Midfielder",
    DOB: "N/A",
    img: midfielderPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },

  // Attackers
  {
    name: "(9) Oli Baron",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Jordan Moore",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Jordan Mercer",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Andy Pye",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 2,
  },
  {
    name: "(1) Josh Robinson",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 1,
  },
  {
    name: "(1) Cameron Liddell",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 20,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
  {
    name: "(1) Harry Whittaker",
    position: "Attacker",
    DOB: "N/A",
    img: attackerPlaceholder,
    appearances: 0,
    goals: 0,
    assists: 0,
    cleanSheets: 0,
    yellowCards: 0,
    redCards: 0,
    manOfTheMatch: 0,
  },
];
